#
#  Copyright 2021 DataStax, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.bookkeeper.component }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "pulsar.name" . }}
    chart: {{ template "pulsar.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.bookkeeper.component }}
    cluster: {{ template "pulsar.fullname" . }}
data:
  zkServers:
    {{- if and .Values.enableTls .Values.tls.zookeeper.enabled }}
    {{- if .Values.extra.zookeepernp }}
    {{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}-ca:2281,{{ template "pulsar.fullname" . }}-{{ .Values.zookeepernp.component }}-ca:2281
    {{- else }}
    {{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}-ca:2281
    {{- end }}
    {{- else }}
    {{- if .Values.extra.zookeepernp }}
    {{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}-ca:2181,{{ template "pulsar.fullname" . }}-{{ .Values.zookeepernp.component }}-ca:2181
    {{- else }}
    {{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}-ca:2181
    {{- end }}
    {{- end }}
  # disable auto recovery on bookies since we will start AutoRecovery in separated pods
  autoRecoveryDaemonEnabled: "false"
  # In k8s always want to use hostname as bookie ID since IP addresses are ephemeral
  useHostNameAsBookieID: "true"
  # HTTP server used by health check
  httpServerEnabled: "true"
  {{- if .Values.function.enableStateStorage }}
    {{- if not (or .Values.extra.stateStorage .Values.function.stateStorageUrlOverride) }}
  # Enable function state storage
  PULSAR_PREFIX_extraServerComponents: org.apache.bookkeeper.stream.server.StreamStorageLifecycleComponent
    {{- end }}
  {{- end }}
  {{- if .Values.tls.bookkeeper.enabled}}
  PULSAR_PREFIX_tlsProvider: OpenSSL
  PULSAR_PREFIX_tlsProviderFactoryClass: org.apache.bookkeeper.tls.TLSContextFactory
  PULSAR_PREFIX_tlsCertificatePath: /pulsar/certs/tls.crt
  PULSAR_PREFIX_tlsKeyStoreType: PEM
  PULSAR_PREFIX_tlsKeyStore: /pulsar/tls-pk8.key
  PULSAR_PREFIX_tlsTrustStoreType: PEM
  PULSAR_PREFIX_bookkeeperTLSClientAuthentication: "true"
  {{- if or .Values.secrets .Values.createCertificates.selfSigned.enabled}}
  PULSAR_PREFIX_bookkeeperTLSTrustCertsFilePath: /pulsar/certs/ca.crt
  {{- else }}
  PULSAR_PREFIX_bookkeeperTLSTrustCertsFilePath: "{{ .Values.tlsCaPath }}/{{ .Values.tlsCaCert }}"
  {{- end }}
  {{- end }}
{{ toYaml .Values.bookkeeper.configData | indent 2 }}
  # Workaround for double-quoted values in old values files
  BOOKIE_MEM: {{ .Values.bookkeeper.configData.BOOKIE_MEM }}
  BOOKIE_GC: {{ .Values.bookkeeper.configData.BOOKIE_GC }}
